/* src/config.h.  Generated by CMake from config.h.cmake  */

/* Package info */
#define PACKAGE "@PROJECT_NAME@"
#define PACKAGE_NAME "@PROJECT_NAME@"
#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define PACKAGE_STRING "@PROJECT_NAME@ @PROJECT_VERSION@"
#define PACKAGE_TARNAME "@PROJECT_NAME@"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define VERSION "@PROJECT_VERSION@"

/* Host info */
#define HOST_TYPE "@HOST_TYPE@"
#define HOST_CPU "@HOST_CPU@"

/* Compiler info */
#define COMPILER_VENDOR "@COMPILER_VENDOR@"
#define COMPILER_VERSION "@COMPILER_VERSION@"

/* SIMD support */
#cmakedefine HAVE_SSE 1
#cmakedefine HAVE_AVX 1
#cmakedefine HAVE_FMA3 1
#cmakedefine DISABLE_SSE 1
#cmakedefine DISABLE_AVX 1
#cmakedefine DISABLE_FMA 1

/* MPI */
#cmakedefine MPI_ENABLED 1

/* BEAGLE - not included in yvyra */
/* #undef BEAGLE_ENABLED */
/* #undef BEAGLE_V3_ENABLED */

/* Readline */
#cmakedefine HAVE_LIBREADLINE 1
#cmakedefine HAVE_READLINE_READLINE_H 1
#cmakedefine HAVE_READLINE_H 1
#cmakedefine HAVE_READLINE_HISTORY_H 1
#cmakedefine HAVE_HISTORY_H 1
#cmakedefine HAVE_READLINE_HISTORY 1

/* Standard headers */
#cmakedefine HAVE_FLOAT_H 1
#cmakedefine HAVE_LIMITS_H 1
#cmakedefine HAVE_UNISTD_H 1
#define HAVE_LIBM 1
#define STDC_HEADERS 1
